# Generated by Django 4.0.4 on 2022-06-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_rename_vilidity_subscription_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=216, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=216, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Feature2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=216, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='icon/%Y%m%d')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', 'order'),
            },
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='testSeries/thumbnail/%Y%m%d')),
                ('thumbnail2', models.ImageField(blank=True, null=True, upload_to='testSeries/thumbnail/%Y%m%d')),
                ('about', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Hinglish', 'Hinglish')], max_length=512, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(blank=True, default=True, null=True)),
                ('category', models.ManyToManyField(to='test_series.category')),
                ('faq', models.ManyToManyField(to='account.faq')),
                ('feature', models.ManyToManyField(to='test_series.feature')),
                ('feature2', models.ManyToManyField(to='test_series.feature2')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
