# Generated by Django 4.0.4 on 2022-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_vilidity_subscription_validity'),
        ('test_series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature2',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='testseries',
            name='category',
            field=models.ManyToManyField(blank=True, to='test_series.category'),
        ),
        migrations.AlterField(
            model_name='testseries',
            name='faq',
            field=models.ManyToManyField(blank=True, to='account.faq'),
        ),
        migrations.AlterField(
            model_name='testseries',
            name='feature',
            field=models.ManyToManyField(blank=True, to='test_series.feature'),
        ),
        migrations.AlterField(
            model_name='testseries',
            name='feature2',
            field=models.ManyToManyField(blank=True, to='test_series.feature2'),
        ),
    ]
