# Generated by Django 4.0.4 on 2022-06-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0002_feature2_description_alter_testseries_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('publish', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Hinglish', 'Hinglish')], max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('access_type', models.CharField(blank=True, choices=[('free', 'free'), ('paid', 'paid')], max_length=512, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('chapter', 'chapter'), ('subject', 'subject'), ('full', 'full')], max_length=512, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, to='test_series.testsetcategory')),
            ],
            options={
                'ordering': ('-created_at', 'order'),
            },
        ),
        migrations.AddField(
            model_name='testseries',
            name='testset',
            field=models.ManyToManyField(blank=True, to='test_series.testset'),
        ),
    ]
