# Generated by Django 4.0.4 on 2022-06-26 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0004_rename_category_testset_testset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('mcq', 'mcq'), ('cq', 'cq'), ('tf', 'tf')], max_length=512, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('max_time', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=512, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('publish', models.BooleanField(blank=True, default=True, null=True)),
                ('testset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_series.testset')),
            ],
            options={
                'ordering': ('-created_at', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('option', models.CharField(blank=True, max_length=512, null=True)),
                ('correct_status', models.BooleanField(blank=True, default=False, null=True)),
                ('correct_marks', models.FloatField(blank=True, null=True)),
                ('incorrect_marks', models.FloatField(blank=True, default=0, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_series.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
