# Generated by Django 4.0.4 on 2022-06-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0007_testsetquestion_remove_question_publish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsetquestion',
            old_name='lecture',
            new_name='question',
        ),
    ]
