# Generated by Django 4.0.4 on 2022-06-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0008_rename_lecture_testsetquestion_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('option', models.CharField(blank=True, max_length=512, null=True)),
                ('correct_status', models.BooleanField(blank=True, default=False, null=True)),
                ('correct_marks', models.FloatField(blank=True, default=0, null=True)),
                ('incorrect_marks', models.FloatField(blank=True, default=0, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_series.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
