# Generated by Django 4.0.4 on 2022-06-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0009_option_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsetquestion',
            name='section',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
