# Generated by Django 4.0.4 on 2022-07-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0011_alter_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='correct_marks',
            new_name='marks',
        ),
        migrations.RemoveField(
            model_name='option',
            name='incorrect_marks',
        ),
    ]
