# Generated by Django 4.0.4 on 2022-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0012_rename_correct_marks_option_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testseries',
            name='mrp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='testseries',
            name='validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
