# Generated by Django 4.0.4 on 2022-05-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contactus_requestcallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Course', 'Course'), ('TestSeries', 'TestSeries'), ('Other', 'Other')], max_length=512, null=True)),
                ('question', models.CharField(blank=True, max_length=1024, null=True)),
                ('answer', models.CharField(blank=True, max_length=2048, null=True)),
                ('publish', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
