# Generated by Django 4.0.4 on 2022-05-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='vilidity',
            new_name='validity',
        ),
    ]
