# Generated by Django 4.0.4 on 2022-06-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_vilidity_subscription_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(blank=True, choices=[('course', 'course'), ('testseries', 'testseries')], max_length=216, null=True),
        ),
    ]
