# Generated by Django 4.0.4 on 2022-06-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0002_feature2_description_alter_testseries_category_and_more'),
        ('account', '0007_alter_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='testseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_series.testseries'),
        ),
    ]
