# Generated by Django 4.0.4 on 2022-06-30 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0010_testsetquestion_section'),
        ('account', '0011_usertestset_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestset',
            name='testseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_series.testseries'),
        ),
    ]
