# Generated by Django 4.0.4 on 2022-07-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_usertestset_testseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestsetanswer',
            name='status',
            field=models.CharField(blank=True, choices=[('answered', 'answered'), ('not_answer', 'not_answer'), ('not_visited', 'not_visited'), ('review_marked', 'review_marked')], max_length=512, null=True),
        ),
    ]
