# Generated by Django 4.0.4 on 2022-07-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_usertestsetanswer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertestsetanswer',
            old_name='option',
            new_name='selected_option',
        ),
    ]
