# Generated by Django 4.0.4 on 2022-07-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_usertestset_report_data_usertestset_report_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestsetanswer',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='usertestsetanswer',
            name='started_at',
        ),
        migrations.AddField(
            model_name='usertestsetanswer',
            name='check_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usertestsetanswer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertestsetanswer',
            name='selected_option_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
