# Generated by Django 4.2.5 on 2023-09-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_userlecturedoubt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=512, null=True)),
                ('password', models.EmailField(blank=True, max_length=216, null=True)),
            ],
        ),
    ]
