# Generated by Django 4.2.5 on 2023-09-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user',
            new_name='username',
        ),
    ]
