# Generated by Django 4.0.4 on 2022-07-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0022_course_mrp_course_validity'),
        ('test_series', '0013_testseries_mrp_testseries_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('percent', 'percent'), ('fixed_amount', 'Fixed Amout')], default='percent', max_length=20)),
                ('value', models.PositiveIntegerField(default=0)),
                ('usage_limit', models.PositiveIntegerField(default=0)),
                ('used', models.PositiveIntegerField(default=0)),
                ('valid', models.BooleanField(default=True)),
                ('course_category', models.ManyToManyField(blank=True, to='course.category')),
                ('courses', models.ManyToManyField(blank=True, to='course.course')),
                ('testseies', models.ManyToManyField(blank=True, to='test_series.testseries')),
                ('testseies_category', models.ManyToManyField(blank=True, to='test_series.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
