# Generated by Django 4.0.4 on 2022-07-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='testseies',
            new_name='testseries',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='testseies_category',
            new_name='testseries_category',
        ),
    ]
