# Generated by Django 4.0.4 on 2022-05-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='instructor/%Y%m%d')),
                ('bio', models.CharField(blank=True, max_length=2048, null=True)),
                ('tags', models.CharField(blank=True, max_length=2048, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
