# Generated by Django 4.0.4 on 2022-05-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_instructor_options_instructor_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=216, null=True)),
                ('type', models.CharField(blank=True, choices=[('Academic', 'Academic'), ('NonAcademic', 'NonAcademic')], max_length=216, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=216, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/%Y%m%d')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course/thumbnail/%Y%m%d')),
                ('thumbnail2', models.ImageField(blank=True, null=True, upload_to='course/thumbnail/%Y%m%d')),
                ('about', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Hinglish', 'Hinglish')], max_length=512, null=True)),
                ('mrp', models.FloatField(blank=True, default=0, null=True)),
                ('selling_price', models.FloatField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(blank=True, default=True, null=True)),
                ('feature', models.ManyToManyField(null=True, to='course.feature')),
                ('instructor', models.ManyToManyField(null=True, to='course.instructor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
