# Generated by Django 4.0.4 on 2022-05-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_category_feature_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(to='course.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='feature',
            field=models.ManyToManyField(to='course.feature'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(to='course.instructor'),
        ),
    ]
