# Generated by Django 4.0.4 on 2022-05-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_faq'),
        ('course', '0004_course_category_alter_course_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.ManyToManyField(to='account.faq'),
        ),
    ]
