# Generated by Django 4.0.4 on 2022-05-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-created_at',)},
        ),
    ]
