# Generated by Django 4.0.4 on 2022-05-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icon/%Y%m%d'),
        ),
    ]
