# Generated by Django 4.0.4 on 2022-06-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_lecture_course_lecture_coursesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
