# Generated by Django 4.0.4 on 2022-06-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_lecture_options_lecture_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
