# Generated by Django 4.0.4 on 2022-06-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_resources_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='publish',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
