# Generated by Django 4.0.4 on 2022-06-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_resources_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='coursesection',
        ),
        migrations.AddField(
            model_name='coursesection',
            name='lecture',
            field=models.ManyToManyField(blank=True, to='course.lecture'),
        ),
    ]
