# Generated by Django 4.0.4 on 2022-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_subscription_testseries'),
        ('course', '0015_remove_lecture_coursesection_coursesection_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='coursesection',
            field=models.ManyToManyField(blank=True, to='course.coursesection'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(blank=True, to='course.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faq',
            field=models.ManyToManyField(blank=True, to='account.faq'),
        ),
        migrations.AlterField(
            model_name='course',
            name='feature',
            field=models.ManyToManyField(blank=True, to='course.feature'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(blank=True, to='course.instructor'),
        ),
    ]
