# Generated by Django 4.0.4 on 2022-06-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_coursesection_course_course_coursesection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='parent_coursesection',
        ),
    ]
