# Generated by Django 4.0.4 on 2022-06-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_remove_coursesection_parent_coursesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='order',
        ),
        migrations.CreateModel(
            name='CoursesectionLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('coursesection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursesection')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecture')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
