# Generated by Django 4.0.4 on 2022-06-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_lecture_options_remove_lecture_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='lecture',
        ),
        migrations.AddField(
            model_name='coursesection',
            name='lecture',
            field=models.ManyToManyField(blank=True, through='course.CoursesectionLecture', to='course.lecture'),
        ),
    ]
