# Generated by Django 4.0.4 on 2022-06-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_alter_coursesection_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesectionlecture',
            name='publish',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
