# Generated by Django 4.0.4 on 2022-06-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_coursesectionlecture_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='mrp',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='selling_price',
        ),
    ]
