# Generated by Django 4.0.4 on 2022-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_rename_mrp_course_price_remove_course_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mrp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
