# Generated by Django 4.0.4 on 2022-08-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_course_mrp_course_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesectionlecture',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
