# Generated by Django 4.0.4 on 2022-06-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_posted_by_bloguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
