# Generated by Django 4.0.4 on 2022-08-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_rename_testseies_coupon_testseries_and_more'),
        ('order', '0005_payment_transation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coupon.coupon'),
        ),
    ]
