# Generated by Django 4.0.4 on 2022-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cart_extra_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='extra',
        ),
        migrations.AddField(
            model_name='productquantity',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='coupon_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
